####### Settings for the TWITTER API

TWITTER = {
    "CONSUMER_KEY": "Xrqw0NhwCVMjM4WX6WTa1QKk5",
    "CONSUMER_SECRET": "B0oLIoE4owSt0drdkfkQuZhG1LaCroGUKgeWU1tgi45BgnCrqx",
    "ACCESS_TOKEN": "2786100177-UFSLVFhio3kzCNdEKyMn18CHpwli4QAzIA5WrUH",
    "ACCESS_TOKEN_SECRET": "4Yk0EtwjOPUizyGlfKMEkGFUvFVHzOFhBppW0y3z8hVLp"
}
